default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DB_USER') { Rails.application.credentials.dig(:database, :username) } %>
  password: <%= ENV.fetch('DB_PASSWORD') { Rails.application.credentials.dig(:database, :password) } %>
  host: <%= ENV.fetch('DB_HOST') { Rails.application.credentials.dig(:database, :host) } %>
  port: <%= ENV.fetch('DB_PORT', 5432) %>

development:
  <<: *default
  database: <%= Rails.application.credentials.dig(:database, :name) || 'kw_app_development' %>

staging:
  <<: *default
  database: <%= ENV.fetch('STAGING_DATABASE_NAME') { Rails.application.credentials.dig(:database, :name) || 'kw_app_staging' } %>
  username: <%= ENV.fetch('STAGING_DATABASE_USERNAME') { Rails.application.credentials.dig(:database, :username) } %>
  password: <%= ENV.fetch('STAGING_DATABASE_PASSWORD') { Rails.application.credentials.dig(:database, :password) } %>
  host: <%= ENV.fetch('DB_HOST') { Rails.application.credentials.dig(:database, :host) } %>
  port: <%= ENV.fetch('DB_PORT', 5432) %>

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:database, :name) || 'kw_app_production' %>
  username: <%= ENV.fetch('POSTGRES_USER') { Rails.application.credentials.dig(:database, :username) } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { Rails.application.credentials.dig(:database, :password) } %>
  host: <%= ENV.fetch('DB_HOST') { Rails.application.credentials.dig(:database, :host) } %>
  port: 5432

test:
  <<: *default
  database: kw_app_test