default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DB_USER', 'dev-user') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'dev-password') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: <%= ENV.fetch('DB_PORT', 5432) %>

development:
  <<: *default
  database: kw_app_development

staging:
  <<: *default
  database: <%= ENV.fetch('STAGING_DATABASE_NAME', 'kw_app_staging') %>
  username: <%= ENV.fetch('STAGING_DATABASE_USERNAME', 'staging_user') %>
  password: <%= ENV["STAGING_DATABASE_PASSWORD"] %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: <%= ENV.fetch('DB_PORT', 5432) %>

production:
  <<: *default
  database: kw_app_production
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: 5432

test:
  <<: *default
  database: kw_app_test
