name: Deploy
concurrency:
  group: production
  cancel-in-progress: true
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      KAMAL_REGISTRY_USERNAME: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
      RAILS_ENV: production
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      PRODUCTION_DATABASE_NAME: ${{ secrets.PRODUCTION_DATABASE_NAME }}
      PRODUCTION_DATABASE_USERNAME: ${{ secrets.PRODUCTION_DATABASE_USERNAME }}
      PRODUCTION_DATABASE_PASSWORD: ${{ secrets.PRODUCTION_DATABASE_PASSWORD }}
      PRODUCTION_DATABASE_HOST: ${{ secrets.PRODUCTION_DATABASE_HOST }}
      REDIS_URL_SIDEKIQ: ${{ secrets.REDIS_URL_SIDEKIQ }}
      STRAVA_CLIENT: ${{ secrets.STRAVA_CLIENT }}
      STRAVA_SECRET: ${{ secrets.STRAVA_SECRET }}
      DOTPAY_PASSWORD: ${{ secrets.DOTPAY_PASSWORD }}
      MAILGUN_LOGIN: ${{ secrets.MAILGUN_LOGIN }}
      MAILGUN_PASSWORD: ${{ secrets.MAILGUN_PASSWORD }}
      OPENSTACK_TENANT: ${{ secrets.OPENSTACK_TENANT }}
      OPENSTACK_USERNAME: ${{ secrets.OPENSTACK_USERNAME }}
      OPENSTACK_API_KEY: ${{ secrets.OPENSTACK_API_KEY }}
      METEOBLUE_KEY: ${{ secrets.METEOBLUE_KEY }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      DB_HOST: kw-app-postgres
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.7
          bundler-cache: true
      - run: gem install kamal
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
          password: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
      - uses: docker/setup-buildx-action@v3
      - run: kamal lock release
      - run: kamal redeploy
      - name: Cleanup old Docker images and containers
        run: kamal prune all
